# Generated by Django 5.0.6 on 2024-05-24 13:43

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
