# Generated by Django 5.0.6 on 2024-05-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="slug",
        ),
    ]
