# Generated by Django 5.0.6 on 2024-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_publication_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="user",
            new_name="object_id",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="attached_url",
        ),
        migrations.AddField(
            model_name="publication",
            name="attached_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
