# Generated by Django 5.0.6 on 2024-06-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_moderators"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Publication",
        ),
    ]
