# Generated by Django 5.0.6 on 2024-06-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_publication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="object_id",
            new_name="author_id",
        ),
    ]
