# Generated by Django 5.0.6 on 2024-07-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_chat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="message",
            field=models.ManyToManyField(related_name="messages", to="users.message"),
        ),
    ]
