# Generated by Django 5.0.6 on 2024-05-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_tutorialsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="tutorialsection",
            options={"ordering": ["order"]},
        ),
        migrations.RenameField(
            model_name="tutorialsection",
            old_name="code_example",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="tutorialsection",
            name="code_explanation",
        ),
        migrations.RemoveField(
            model_name="tutorialsection",
            name="description",
        ),
        migrations.AlterField(
            model_name="tutorialsection",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="app.programminglanguage",
            ),
        ),
    ]
