# Generated by Django 5.0.6 on 2024-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_programminglanguage_thread_status_thread_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
