# Generated by Django 5.0.6 on 2024-05-26 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_programminglanguage_alter_tutorialsection_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreadAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("context", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="images/answers/")),
                ("file", models.FileField(blank=True, upload_to="files/answers/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
