# Generated by Django 5.0.6 on 2024-05-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_treadanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="treadanswer",
            name="thread",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_answer",
                to="app.thread",
            ),
        ),
    ]
