# Generated by Django 5.0.6 on 2024-05-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_treadanswer_threadanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="programminglanguage",
            name="template_path",
            field=models.CharField(default="", max_length=511),
        ),
    ]
