# Generated by Django 5.0.6 on 2024-05-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_programminglanguage_template_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programminglanguage",
            name="template_path",
            field=models.CharField(default="/", max_length=511),
        ),
        migrations.DeleteModel(
            name="TutorialSection",
        ),
    ]
