# Generated by Django 5.0.6 on 2024-05-31 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_tutorialpage_subsection_delete_tutorialsection"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("context", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="images/answers/")),
                ("file", models.FileField(blank=True, upload_to="files/answers/")),
                ("object_id", models.PositiveIntegerField(default="")),
                (
                    "content_type",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ThreadAnswer",
        ),
    ]
