# Generated by Django 5.0.6 on 2024-06-09 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_community_users"),
        ("users", "0009_moderators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="followers",
            field=models.ManyToManyField(
                null=True,
                related_name="community_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="community",
            name="posts",
        ),
        migrations.AddField(
            model_name="community",
            name="posts",
            field=models.ManyToManyField(blank=True, null=True, related_name="posts", to="users.publication"),
        ),
    ]
