# Generated by Django 5.0.6 on 2024-06-09 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_community_followers_remove_community_posts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="followers",
            field=models.ManyToManyField(related_name="community_followers", to=settings.AUTH_USER_MODEL),
        ),
    ]
