# Generated by Django 5.0.6 on 2024-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_community_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
