# Generated by Django 5.0.6 on 2024-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_community_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="is_private",
            field=models.BooleanField(choices=[("True", "Private"), ("False", "Public")], default=False),
        ),
    ]
