# Generated by Django 5.0.6 on 2024-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_community_is_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
