# Generated by Django 5.0.6 on 2024-06-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_community_is_private"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Community",
        ),
    ]
