# Generated by Django 5.0.6 on 2024-06-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_rename_object_id_thread_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communityfollowers",
            name="community",
        ),
        migrations.RemoveField(
            model_name="communityfollowers",
            name="user",
        ),
        migrations.DeleteModel(
            name="Community",
        ),
        migrations.DeleteModel(
            name="CommunityFollowers",
        ),
    ]
