# Generated by Django 5.0.6 on 2024-06-13 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_communityfollowers_accepted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communityfollowers",
            name="accepted",
        ),
        migrations.AlterField(
            model_name="communityfollowers",
            name="is_follow",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CommunityFollowRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("send_status", models.BooleanField(default=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cfr",
                        to="community.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ufr",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
