# Generated by Django 5.0.6 on 2024-06-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_remove_communityfollowers_accepted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communityfollowrequests",
            name="rejected",
        ),
    ]
