# Generated by Django 5.0.6 on 2024-06-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_remove_communityfollowers_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityfollowrequests",
            name="send_status",
            field=models.BooleanField(default=False),
        ),
    ]
