# Generated by Django 5.0.6 on 2024-06-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_blacklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banned",
                to="community.communityfollowers",
            ),
        ),
    ]
